(**pp -package pa_ppx_parsetree_via_parsetree -syntax camlp5r *)
[@@@"ocaml.text" "attribute";];
<:attribute< [@ $attrid:s$ $list:x$] >>;
<:attribute< [@ $attrid:s$ : $list:x$] >>;
<:attribute< [@ $attrid:s$ : $x$] >>;
<:attribute< [@ $attrid:s$ ? $x1$] >>;
<:attribute< [@ $attrid:s$ ? $x1$ when $x2$] >>;
<:attribute< [@ $attrid:s$ ? $x1$ $expropt:ox2$] >>;
[@@@"ocaml.text" "extension";];
<:extension< [% $attrid:s$ $list:x$] >>;
<:extension< [% $attrid:s$ : $list:x$] >>;
<:extension< [% $attrid:s$ : $x$] >>;
<:extension< [% $attrid:s$ ? $x1$] >>;
<:extension< [% $attrid:s$ ? $x1$ when $x2$] >>;
<:extension< [% $attrid:s$ ? $x1$ $expropt:ox2$] >>;
[@@@"ocaml.text" "attributes";];
[@@@"ocaml.text" "payload";];
[@@@"ocaml.text" "core_type";];
<:core_type< _ >> ;
<:core_type< ' $lid:s$ >> ;
<:core_type< $label:x1$ $x2$ -> $x3$ >> ;
<:core_type< $tuplelist:lx$ >> ;
<:core_type< $list:lx$ $longid:x$ >> ;
<:core_type< < $list:lx$ $closedflag:x$ > >> ;
<:core_type< $list:lx$ # $longid:x$ >> ;
<:core_type< $x$ as ' $lid:s$ >> ;
<:core_type< [ $closedflag:x$ $list:lx1$ $opt:None$ ] >> ;
<:core_type< [ $closedflag:x$ $list:lx1$ > $list:lx2$ ] >> ;
<:core_type< [ $closedflag:x$ $list:lx1$ $opt:olx2$ ] >> ;
<:core_type< [< $list:lx1$ ] >> ;
{Parsetree.ptyp_desc = Parsetree.Ptyp_poly lx x; Parsetree.ptyp_loc = __loc__; Parsetree.ptyp_loc_stack = []; Parsetree.ptyp_attributes = []};
<:core_type< (module $longid:x$ with $list:xf2$) >>;
<:core_type< [% $attrid:s$ $list:x$] >>;
<:core_type< [% $attrid:s$ : $list:x$] >>;
<:core_type< [% $attrid:s$ : $x$] >>;
<:core_type< [% $attrid:s$ ? $x1$] >>;
<:core_type< [% $attrid:s$ ? $x1$ when $x2$] >>;
<:core_type< [% $attrid:s$ ? $x1$ $expropt:ox2$] >>;
[@@@"ocaml.text" "core_type_desc";];
[@@@"ocaml.text" "package_type";];
[@@@"ocaml.text" "row_field";];
[@@@"ocaml.text" "row_field_desc";];
[@@@"ocaml.text" "object_field";];
[@@@"ocaml.text" "object_field_desc";];
[@@@"ocaml.text" "pattern";];
<:pattern< _ >> ;
<:pattern<  $lid:s$ >> ;
<:pattern< $x1$ as $lid:s$ >> ;
<:pattern< $int:s$ >> ;
<:pattern< $int32:s$ >> ;
<:pattern< $int64:s$ >> ;
<:pattern< $nativeint:s$ >> ;
<:pattern< $char:x$ >> ;
<:pattern< $string:s1$ >> ;
<:pattern< $string:s1$ $delim:s2$ >> ;
{Parsetree.ppat_desc = Parsetree.Ppat_constant (Parsetree.Pconst_string s1 __loc__ os2); Parsetree.ppat_loc = __loc__; Parsetree.ppat_loc_stack = []; Parsetree.ppat_attributes = []};
<:pattern< $float:sxf1$ >> ;
{Parsetree.ppat_desc = Parsetree.Ppat_constant x; Parsetree.ppat_loc = __loc__; Parsetree.ppat_loc_stack = []; Parsetree.ppat_attributes = []};
<:pattern< $constant:x1$ .. $constant:x2$ >> ;
<:pattern<  $tuplelist:lx$ >>;
<:pattern< $longid:x$ >>;
<:pattern< $longid:x$ (type $list:lxxf1$) $lxxf2$ >>;
<:pattern< $longid:x$ $pattopt:olxx$ >>;
<:pattern< ` $id:x1$ >>;
<:pattern< ` $id:x1$ $x2$ >>;
<:pattern< ` $id:x1$ $pattopt:ox2$ >>;
<:pattern< { $list:lxx$ $closedflag:x$ } >> ;
<:pattern< [| $list:lx$ |] >>;
<:pattern< $x1$ | $x2$ >>;
<:pattern< ( $x1$ : $x2$ ) >>;
<:pattern< # $longid:x$ >>;
<:pattern< lazy $x$ >>;
<:pattern< (module _) >>;
<:pattern< (module $uid:s$) >>;
<:pattern< (module $opt:os$) >>;
<:pattern< exception $x$ >> ;
<:pattern< [% $attrid:s$ $list:x$] >>;
<:pattern< [% $attrid:s$ : $list:x$] >>;
<:pattern< [% $attrid:s$ : $x$] >>;
<:pattern< [% $attrid:s$ ? $x1$] >>;
<:pattern< [% $attrid:s$ ? $x1$ when $x2$] >>;
<:pattern< [% $attrid:s$ ? $x1$ $expropt:ox2$] >>;
<:pattern< $longid:x$ . $x2$ >>;
[@@@"ocaml.text" "pattern_desc";];
[@@@"ocaml.text" "expression";];
<:expression< $lid:s$ >>;
<:expression< $longid:x$ . $lid:s$ >>;
<:expression< $int:s$ >> ;
<:expression< $int32:s$ >> ;
<:expression< $int64:s$ >> ;
<:expression< $nativeint:s$ >> ;
<:expression< $char:x$ >> ;
<:expression< $string:s1$ >> ;
<:expression< $string:s1$ $delim:s2$ >> ;
{Parsetree.pexp_desc = Parsetree.Pexp_constant (Parsetree.Pconst_string s1 __loc__ os2); Parsetree.pexp_loc = __loc__; Parsetree.pexp_loc_stack = []; Parsetree.pexp_attributes = []};
<:expression< $float:sxf1$ >> ;
<:expression< $constant:x$ >> ;
<:expression< let $recflag:x1$ $list:lx$ in $x2$ >>;
<:expression< function $list:lx$ >>;
<:expression< fun $label:x1$ ( $x3$ ) -> $x4$ >>;
<:expression< fun $label:x1$ ( $x3$ = $x2$ ) -> $x4$ >>;
<:expression< fun $label:x1$ ( $x3$ $expropt:ox2$ ) -> $x4$ >>;
<:expression< $x$ $list:lxx$ >>;
<:expression< match $x$ with $list:lx$ >>;
<:expression< try $x$ with $list:lx$ >>;
<:expression<  $tuplelist:lx$ >>;
<:expression< $longid:x$ >>;
<:expression< $longid:x$ $x2$ >>;
<:expression< $longid:x$ $expropt:ox2$ >>;
<:expression< ` $id:x1$ >>;
<:expression< ` $id:x1$ $x2$ >>;
<:expression< ` $id:x1$ $expropt:ox2$ >>;
<:expression< { $list:lxx$ } >>;
<:expression< { $x$ with $list:lxx$ } >>;
<:expression< { $withe:ox$ $list:lxx$ } >>;
<:expression< $x1$ . $lid:s$ >>;
<:expression< $x1$ . $longid:x$ . $lid:s$ >>;
{Parsetree.pexp_desc = Parsetree.Pexp_field x1 {Location.txt = x; Location.loc = __loc__}; Parsetree.pexp_loc = __loc__; Parsetree.pexp_loc_stack = []; Parsetree.pexp_attributes = []};
<:expression< $x1$ . $lid:s$ <- $x3$ >>;
<:expression< $x1$ . $longid:x$ . $lid:s$ <- $x3$ >>;
{Parsetree.pexp_desc = Parsetree.Pexp_setfield x1 {Location.txt = x; Location.loc = __loc__} x3; Parsetree.pexp_loc = __loc__; Parsetree.pexp_loc_stack = []; Parsetree.pexp_attributes = []};
<:expression< [| $list:lx$ |] >>;
<:expression< if $x1$ then $x2$ >>;
<:expression< if $x1$ then $x2$ else $x3$ >>;
<:expression< if $x1$ then $x2$ $expropt:ox3$ >>;
<:expression< $x1$ ; $x2$ >>;
<:expression< while $x1$ do $x2$ done >>;
<:expression< for $x1$ = $x2$ to $x3$ do $x5$ done >>;
<:expression< for $x1$ = $x2$ downto $x3$ do $x5$ done >>;
<:expression< for $x1$ = $x2$ $dirflag:x4$ $x3$ do $x5$ done >>;
<:expression< ( $x1$ : $x2$ ) >>;
<:expression< ( $x1$ :> $x3$ ) >>;
<:expression< ( $x1$ : $x2$ :> $x3$ ) >>;
<:expression< ( $x1$ $ctypopt:ox2$ :> $x3$ ) >>;
<:expression< $x1$ # $lid:x$ >>;
<:expression< new $lid:s$ >>;
<:expression< new $longid:x$ . $lid:s$ >>;
{Parsetree.pexp_desc = Parsetree.Pexp_new {Location.txt = x; Location.loc = __loc__}; Parsetree.pexp_loc = __loc__; Parsetree.pexp_loc_stack = []; Parsetree.pexp_attributes = []};
<:expression< $lid:x$ <- $x2$ >>;
<:expression< {< $list:lxx$ >} >>;
<:expression< let module _ = $me$ in $x2$ >>;
<:expression< let module $uid:s$ = $me$ in $x2$ >>;
<:expression< let module $opt:os$ = $me$ in $x2$ >>;
<:expression< let $excon:x1$ in $x2$ >>;
<:expression< assert $x$ >>;
<:expression< lazy $x$ >>;
{Parsetree.pexp_desc = Parsetree.Pexp_poly x1 None; Parsetree.pexp_loc = __loc__; Parsetree.pexp_loc_stack = []; Parsetree.pexp_attributes = []};
{Parsetree.pexp_desc = Parsetree.Pexp_poly x1 (Some x2); Parsetree.pexp_loc = __loc__; Parsetree.pexp_loc_stack = []; Parsetree.pexp_attributes = []};
{Parsetree.pexp_desc = Parsetree.Pexp_poly x1 ox2; Parsetree.pexp_loc = __loc__; Parsetree.pexp_loc_stack = []; Parsetree.pexp_attributes = []};
<:expression< object $patt:x$ $list:lx$  end >>;
<:expression< fun (type $lid:s$) -> $x2$ >> ;
<:expression< (module $me$) >> ;
<:expression< let open $overrideflag:x1$ $me$ in $x2$ >> ;
<:expression< $letop:x1$ $list:lx$ in $x2$ >>;
<:expression< [% $attrid:s$ $list:x$] >>;
<:expression< [% $attrid:s$ : $list:x$] >>;
<:expression< [% $attrid:s$ : $x$] >>;
<:expression< [% $attrid:s$ ? $x1$] >>;
<:expression< [% $attrid:s$ ? $x1$ when $x2$] >>;
<:expression< [% $attrid:s$ ? $x1$ $expropt:ox2$] >>;
{Parsetree.pexp_desc = Parsetree.Pexp_unreachable; Parsetree.pexp_loc = __loc__; Parsetree.pexp_loc_stack = []; Parsetree.pexp_attributes = []};
[@@@"ocaml.text" "expression_desc";];
[@@@"ocaml.text" "case";];
<:case< $x1$ -> $x3$ >> ;
<:case< $x1$ when $x2$ -> $x3$ >> ;
<:case< $x1$ $wheno:ox2$ -> $x3$ >> ;
[@@@"ocaml.text" "letop";];
[@@@"ocaml.text" "binding_op";];
[@@@"ocaml.text" "value_description";];
[@@@"ocaml.text" "type_declaration";];
[@@@"ocaml.text" "type_kind";];
[@@@"ocaml.text" "label_declaration";];
[@@@"ocaml.text" "constructor_declaration";];
[@@@"ocaml.text" "constructor_arguments";];
[@@@"ocaml.text" "type_extension";];
[@@@"ocaml.text" "extension_constructor";];
[@@@"ocaml.text" "type_exception";];
[@@@"ocaml.text" "extension_constructor_kind";];
[@@@"ocaml.text" "class_type";];
[@@@"ocaml.text" "class_type_desc";];
[@@@"ocaml.text" "class_signature";];
[@@@"ocaml.text" "class_type_field";];
[@@@"ocaml.text" "class_type_field_desc";];
[@@@"ocaml.text" "class_infos";];
[@@@"ocaml.text" "class_description";];
[@@@"ocaml.text" "class_type_declaration";];
[@@@"ocaml.text" "class_expr";];
[@@@"ocaml.text" "class_expr_desc";];
[@@@"ocaml.text" "class_structure";];
[@@@"ocaml.text" "class_field";];
[@@@"ocaml.text" "class_field_desc";];
[@@@"ocaml.text" "class_field_kind";];
[@@@"ocaml.text" "class_declaration";];
[@@@"ocaml.text" "module_type";];
<:module_type< $longid:x$ >>;
<:module_type< sig $list:x$ end >>;
<:module_type< functor $opt:x$ -> $mt$ >>;
<:module_type< $mt$ with $list:lx$ >>;
<:module_type< module type of $me$ >>;
<:module_type< [% $attrid:s$ $list:x$] >>;
<:module_type< [% $attrid:s$ : $list:x$] >>;
<:module_type< [% $attrid:s$ : $x$] >>;
<:module_type< [% $attrid:s$ ? $x1$] >>;
<:module_type< [% $attrid:s$ ? $x1$ when $x2$] >>;
<:module_type< [% $attrid:s$ ? $x1$ $expropt:ox2$] >>;
[@@@"ocaml.text" "module_type_desc";];
[@@@"ocaml.text" "functor_parameter";];
[@@@"ocaml.text" "signature";];
[@@@"ocaml.text" "signature_item";];
[@@@"ocaml.text" "signature_item_desc";];
[@@@"ocaml.text" "module_declaration";];
[@@@"ocaml.text" "module_substitution";];
[@@@"ocaml.text" "module_type_declaration";];
[@@@"ocaml.text" "open_infos";];
[@@@"ocaml.text" "open_description";];
[@@@"ocaml.text" "open_declaration";];
[@@@"ocaml.text" "include_infos";];
[@@@"ocaml.text" "include_description";];
[@@@"ocaml.text" "include_declaration";];
[@@@"ocaml.text" "with_constraint";];
[@@@"ocaml.text" "module_expr";];
<:module_expr< $longid:x$ >>;
<:module_expr< struct $list:x$ end >>;
<:module_expr< functor $opt:x$ -> $me$ >>;
<:module_expr< $me1$( $me2$ ) >>;
<:module_expr< ( $me$ : $mt$ ) >>;
<:module_expr< [% $attrid:s$ $list:x$] >>;
<:module_expr< [% $attrid:s$ : $list:x$] >>;
<:module_expr< [% $attrid:s$ : $x$] >>;
<:module_expr< [% $attrid:s$ ? $x1$] >>;
<:module_expr< [% $attrid:s$ ? $x1$ when $x2$] >>;
<:module_expr< [% $attrid:s$ ? $x1$ $expropt:ox2$] >>;
[@@@"ocaml.text" "module_expr_desc";];
[@@@"ocaml.text" "structure";];
[@@@"ocaml.text" "structure_item";];
[@@@"ocaml.text" "structure_item_desc";];
[@@@"ocaml.text" "value_binding";];
[@@@"ocaml.text" "module_binding";];
[@@@"ocaml.text" "position";];
[@@@"ocaml.text" "location";];
[@@@"ocaml.text" "located";];
[@@@"ocaml.text" "str_vala";];
[@@@"ocaml.text" "longident_t";];
[@@@"ocaml.text" "ast_constant";];
[@@@"ocaml.text" "arg_label";];
[@@@"ocaml.text" "label";];
[@@@"ocaml.text" "closed_flag";];
[@@@"ocaml.text" "rec_flag";];
[@@@"ocaml.text" "direction_flag";];
[@@@"ocaml.text" "private_flag";];
[@@@"ocaml.text" "mutable_flag";];
[@@@"ocaml.text" "virtual_flag";];
[@@@"ocaml.text" "override_flag";];
[@@@"ocaml.text" "variance";];
[@@@"ocaml.text" "injectivity";];
[@@@"ocaml.text" "constant";];
<:constant< $int:s$ >> ;
<:constant< $int32:s$ >> ;
<:constant< $int64:s$ >> ;
<:constant< $nativeint:s$ >> ;
<:constant< $char:x$ >> ;
<:constant< $string:s1$ >> ;
<:constant< $string:s1$ $delim:s2$ >> ;
Parsetree.Pconst_string s1 __loc__ os2;
<:constant< $float:sxf1$ >> ;
[@@@"ocaml.text" "location_stack";];
[@@@"ocaml.text" "toplevel_phrase";];
[@@@"ocaml.text" "toplevel_directive";];
[@@@"ocaml.text" "directive_argument";];
[@@@"ocaml.text" "directive_argument_desc";];
